export EDITOR="vim"
export PATH=$PATH:/usr/local/go/bin

if [ -f ~/.dotfiles/bash/aliases ]; then
  source ~/.dotfiles/bash/aliases
fi

if [ -f ~/.dotfiles/bash/private_aliases ]; then
  source ~/.dotfiles/bash/private_aliases
fi

if [ -f ~/.dotfiles/bashrc ]; then
  source ~/.dotfiles/bash/bashrc
fi

# Powerline Go
function _update_ps1() {
    PS1="$(~/go/bin/powerline-go -modules "venv,ssh,cwd,perms,git,hg,jobs,exit,root" -cwd-max-depth 5 -error $?)"
}

if [ "$TERM" != "linux" ]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi

#RVM
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
